### PR TITLE
Make simple vagga configuration

### PR DESCRIPTION
**Pull request by anxolerd**
Made this container to run

Made this as simple as I found, so, probably I've missed something.
But at least it works

### CODE REVIEW

**Comment by webknjaz** [comment]
LGTM, but AFAIK python3 doesn't need do be reinstalled. You just need to switch symlink.

**Comment by webknjaz** [comment]
Here you go:
https://github.com/itkpi/events-public/blob/master/vagga.yaml#L9-L10
http://vagga.readthedocs.io/en/latest/build_steps.html#step-PipConfig

``` yaml
- !PipConfig
  python-exe: python3.5
```

**Comment by webknjaz** [comment]
LGTM & needs testing

**Comment by phiNumber** [comment]
works for me too

**Pull request merged**
